# Generated by Django 4.1.7 on 2023-03-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id_senha', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.TextField(max_length=999)),
            ],
        ),
    ]
